// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ExoHdLTFszJz7311LtJ_IYvQ1B0wc7w',
    appId: '1:895041959025:web:328aeed147d66e087957d0',
    messagingSenderId: '895041959025',
    projectId: 'auction-bec64',
    authDomain: 'auction-bec64.firebaseapp.com',
    databaseURL: 'https://auction-bec64-default-rtdb.firebaseio.com',
    storageBucket: 'auction-bec64.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYqYRKh-hRxIkhfhguHJr3PmPAHXGiSSo',
    appId: '1:895041959025:android:010cdb46c4f1364c7957d0',
    messagingSenderId: '895041959025',
    projectId: 'auction-bec64',
    databaseURL: 'https://auction-bec64-default-rtdb.firebaseio.com',
    storageBucket: 'auction-bec64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn-_x8UFbXaKkQBibb_kieelY6oPIlgUk',
    appId: '1:895041959025:ios:a94c65b5220da5277957d0',
    messagingSenderId: '895041959025',
    projectId: 'auction-bec64',
    databaseURL: 'https://auction-bec64-default-rtdb.firebaseio.com',
    storageBucket: 'auction-bec64.appspot.com',
    iosClientId: '895041959025-6jm06tmuhes9ar70vv4917bk7l45145u.apps.googleusercontent.com',
    iosBundleId: 'com.stevenrockarts.auction',
  );
}
